### PR TITLE
* resolved misplaced static singleton instance which caused a nullReference exception…

### PR DESCRIPTION
**Pull request by Mahdad-Baghani**
environment:
: Unity 2019.3.0f3
: JDK 1.8.0_231
=> the problem is in BazaarIAB.cs, line 22, 23: the code tries to create a AndroidJavaClass and call a static function named "instance" on it.
=> since the "instance" func is defined in the BazaarIABPluginBase, I either can create an instance of com.bazaar.BazaarIABPluginBase (line 22 of BazaarIAB.cs) (which I did not try)
=> or I can move "instance" into the derived class, BazaarIABPlugin. in my opinion, this option creates a better hierarchy of parent/child classes since the parent (BazaarPluginBase) should not return an instance of it's derived class.

### CODE REVIEW

**Comment by hojjatjafary** [comment]
I'm agree with you from the software engineering perspective and cleaner code viewpoint, but as it is a static method and there is no type ambiguity this should not cause any crashes!
How do you sure that the crashes are related to this method?

**Comment by Mahdad-Baghani** [comment]
> 
> 
> I'm agree with you from the software engineering perspective and cleaner code viewpoint, but as it is a static method and there is no type ambiguity this should not cause any crashes!
> How do you sure that the crashes are related to this method?

It's not about crashes. The thing is, you just get an nullRefrence back, meaning the that static field of BazaarIAB named "mPlugin" would be set to null, and there would be no interaction possible with CafeBazaar.

**Comment by hojjatjafary** [comment]
OK, I will check it and let you know as soon as I can find some free time.

**Comment by hojjatjafary** [comment]
Hi @Mahdad-Baghani , Can you please pull and test the package. I didn't merged your pull request but did the required changes manually. I also upgraded the Gradle and target api version.
I will publish a new release and mention your help in the Thanks section.
Thanks.

**Comment by Mahdad-Baghani** [comment]
> 
> 
> Hi @Mahdad-Baghani , Can you please pull and test the package. I didn't merged your pull request but did the required changes manually. I also upgraded the Gradle and target api version.
> I will publish a new release and mention your help in the Thanks section.
> Thanks.

thanx for the quick reply. First of all I have to say that I know my commit message is a little bit misleading and borderline offensive. I didn't have an intention to create a pull request when I commited the change locally. But then I deicded to share the fix. I appologize about that. I did rectify the commit message. However at this point, I think it will be impossible to merge the branches since you pushed new commits and there will be merge conflicts. I'll try my lock with other pull requests! thanks.

**Comment by Mahdad-Baghani** [comment]
I reopened the pull request to solve the conflicts just in case someone wanted to follow the lines. I also added a new and more visual test which I used to do the integration test for our next game

**Pull request closed without merging**
